categories:
  - entrepreneurs
  - health-and-fitness
  - travel
  - living-abroad
  - create-change
  - outside-the-box
  - sustainability
  - handbags
  - candles
  - wallets

collections:
   products:
     output: true


# Set pretty permalink
permalink: /:categories/:title/
